import Footer from "@/components/Footer";
import Header from "@/components/Header";
import SessionProvider from "@/components/SessionProvider";
import "@/styles/globals.css";
import { cn } from "@/utils/style";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Noto_Sans_KR } from "next/font/google";
import { ToastContainer } from "react-toastify";

export const noto = Noto_Sans_KR({
  weight: ["400"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={cn(
          "scrollbar overflow-x-hidden bg-[#f3eeea] text-sm",
          "lg:text-base",
          noto.className
        )}
      >
        <SessionProvider session={session}>
          <Header />
          <main className="w-full">{children}</main>
          <Footer />
          <ToastContainer
            position="top-center"
            autoClose={3000}
            closeOnClick
            pauseOnFocusLoss={false}
            theme="dark"
          />
        </SessionProvider>
      </body>
    </html>
  );
}
